name: Daily Task Reminder

on:
  schedule:
    - cron: '55 21 * * *'  # UTC 21:55 = 北京时间 5:55 (提前2小时获取早上数据)
    - cron: '55 12 * * *'  # UTC 12:55 = 北京时间 20:55 (提前1小时获取晚上数据)
  workflow_dispatch:      # 允许手动触发

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run reminder script
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        DATABASE_ID: ${{ secrets.DATABASE_ID }}
        PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        REMINDER_TYPE: ${{ github.event.schedule == '55 12 * * *' && 'evening' || 'morning' }}
        SEND_TIME: ${{ github.event.schedule == '55 12 * * *' && '22:00' || '08:00' }}
      run: |
        echo "PUSHPLUS_TOKEN=${PUSHPLUS_TOKEN:0:8}***"
        python src/main.py
