name: Daily Task Reminder

on:
  schedule:
    - cron: '30 0 * * *'   # UTC 0:30 = 北京时间 8:30
    - cron: '14 14 * * *' # UTC 14:14 = 北京时间 22:14
  workflow_dispatch:      # 允许手动触发

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run reminder script
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        DATABASE_ID: ${{ secrets.DATABASE_ID }}
        PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        REMINDER_TYPE: ${{ github.event.schedule == '14 14 * * *' && 'evening' || 'morning' }}
      run: |
        echo "PUSHPLUS_TOKEN=${PUSHPLUS_TOKEN:0:8}***"  # 安全地打印token前8位
        python src/main.py
